version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:2.9.0
    environment:
      - discovery.type=single-node
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9600:9600 # required for Performance Analyzer
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: opensearch-dashboards
    ports:
      - 127.0.0.1:5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
  fluentd:
    build: .
    ports:
      - 127.0.0.1:24224:24224
      - 127.0.0.1:24224:24224/udp
    environment:
      FLUENTD_CONF: fluentd.conf # Found in fluentd/etc/fluentd.conf
    volumes:
      - ./data:/fluentd/log
      - ./fluentd.conf:/fluentd/etc/fluentd.conf
  app:
    build:
      context: .
      dockerfile: Dockerfile.go.dk
    ports:
      - 127.0.0.1:8080:8080
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: myapp

volumes:
  opensearch-data:
